---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-ops-view
  namespace: monitoring
spec:
  releaseName: kube-ops-view
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kube-ops-view
    version: 1.2.1
  values:
    rbac:
      create: true
    ingress:
      enabled: true
      hostname: ops.hacksm.net
      annotations:
        ingress.pomerium.io/allowed_users: '["matt@matt-white.co.uk"]'
        ingress.pomerium.io/allow_websockets: "true"
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "Kube Ops View"
        forecastle.stakater.com/icon: https://hub.helm.sh/api/chartsvc/v1/assets/stable/kube-ops-view/logo
