---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-url=git@github.com:krangence/k8s-flux.git
            - --git-label=flux-sync
            - --git-email=matt@matt-white.co.uk
            - --git-poll-interval=5m
            - --sync-garbage-collection
            - --manifest-generation=true
            - --listen-metrics=:3031
